language: elixir
elixir:
  - '1.7'
otp_release:
  - '20.3'

env:
  - MIX_ENV=test

script: mix coveralls.travis

deploy:
  provider: script

  script: >-
     mix deps.get &&
     mix hex.config username "$HEX_USERNAME" &&
     mix hex.config key "$HEX_KEY" &&
     mix hex.docs
     mix hex.publish
  on:
    tags: true
