language: elixir
elixir:
  - '1.7'
otp_release:
  - '20.3'

env:
  - MIX_ENV=test

cache:
  directories:
    - _build
    - deps

script: mix coveralls.travis

deploy:
  provider: script

  script: scripts/hex.sh
  on:
    tags: true
